---
so_search_answer_name: "so-ansible-search"
so_search_install_timeout: 1200   # 20 min
so_search_poll_interval: 30
so_search_setup_log: "/root/so-setup.log"
so_search_installed_marker: "/opt/so/state/installed"
